# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4dc7e48ce726820d1630883ef976e7e7d7b3a1b97c8aaedc3b6a97098f347c988a593ba6578d46d15eb3755b5ad83c5700cc0bb5d8d45ab13ca76db230926b25

test:
  secret_key_base: f5aecd20825b19ec56cc5be94d2cbf8b85ccdc456442f8081364d04ff4ece0f646395d1ef0fb6295ccdff1a2e0e35f7d157f023bda939a26fde97b650a3bd26a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
